accent = "#a69f96"
cursor = "#f0ead6"
foreground = "#f0ead6"
background = "#232e37"
selection_foreground = "#232e37"
selection_background = "#f0ead6"

color0 = "#232e37"
color1 = "#e17f47"
color2 = "#7e8b56"
color3 = "#f0ead6"
color4 = "#a69f96"
color5 = "#c080c0"
color6 = "#80c0c0"
color7 = "#f0ead6"
color8 = "#a69f96"
color9 = "#ff9966"
color10 = "#9acd32"
color11 = "#ffffcc"
color12 = "#add8e6"
color13 = "#ffb6c1"
color14 = "#e0ffff"
color15 = "#ffffff"
